--UPGRADE 12
DELETE FROM pois WHERE rowid=57;
DELETE FROM pois WHERE rowid=106;
DELETE FROM pois WHERE rowid=239;
DELETE FROM pois WHERE rowid=243;
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(382,'symbols','Services','ic_symbol_service_turning_point_45','45'' Turning approximately',0,NULL,0,0,0,0,0,1,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(383,'system','system','ic_symbol_service_turning_point_45_contents','ic_symbol_service_turning_point_45_contents',0,NULL,0,0,0,0,0,1,1,1,1,1,1,1,1);
UPDATE pois SET description='50'' Turning approximately' WHERE rowid=39;
UPDATE pois SET description='55'' Turning approximately' WHERE rowid=92;
UPDATE pois SET description='60'' Turning approximately' WHERE rowid=40;
UPDATE pois SET description='65'' Turning approximately' WHERE rowid=91;
UPDATE pois SET description='70'' Turning approximately' WHERE rowid=41;
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(384,'markers','Moorings','ic_marker_mooring_72hr','Mooring 72 hours',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(385,'system','system','ic_marker_mooring_72hr_contents','ic_marker_mooring_72hr_contents',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(388,'markers','Moorings','ic_marker_mooring_5d','Mooring 5 days',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(389,'system','system','ic_marker_mooring_5d_contents','ic_marker_mooring_5d_contents',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(390,'markers','Moorings','ic_marker_mooring_0','Mooring unknown term',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(391,'system','system','ic_marker_mooring_0_contents','ic_marker_mooring_0_contents',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(392,'markers','Moorings','ic_marker_mooring_0bw','BW Mooring',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(393,'system','system','ic_marker_mooring_0bw_contents','ic_marker_mooring_0bw_contents',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(394,'markers','Moorings','ic_marker_mooring_charge','Charged Mooring',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(395,'system','system','ic_marker_mooring_charge_contents','ic_marker_mooring_charge_contents',0,NULL,0,0,0,0,0,0,0,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(396,'symbols','Services','ic_symbol_service_drydock','Dry Dock',0,NULL,0,0,0,0,0,0,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(397,'system','system','ic_symbol_service_drydock_contents','ic_symbol_service_drydock_contents',0,NULL,0,0,0,0,0,0,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(398,'symbols','Services','ic_symbol_service_navigation','Navigation',0,NULL,0,0,0,0,0,0,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(399,'system','system','ic_symbol_service_navigation_contents','ic_symbol_service_navigation_contents',0,NULL,0,0,0,0,0,0,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(400,'markers','Editors','ic_marker_noticeadmin','Admin Only',0,NULL,1,0,0,0,1,1,1,1,1,1,1,1,1);
INSERT INTO pois(rowid,area,category,name,description,orderidx,"action",scope,level07,level08,level09,level10,level11,level12,level13,level14,level15,level16,level17,"filter") VALUES(401,'system','system','ic_marker_noticeadmin_contents','ic_marker_noticeadmin_contents',0,NULL,1,0,0,0,1,1,1,1,1,1,1,1,1);
UPDATE pois SET description='Map Error' WHERE rowid=378;
ALTER TABLE mysettings ADD COLUMN securityfeatures;
CREATE UNIQUE INDEX waterwayguid ON routes (waterwayguid);
UPDATE pois SET description='Good Mooring' WHERE rowid=56;
CREATE INDEX speedUpKeyWaterwayGuid ON tiles ("key", waterwayguid);
CREATE INDEX speedUpGetTile ON tiles ("key");
DROP TABLE _connect;
DROP TABLE _import;
DROP TABLE _locations;
DROP TABLE android_metadata;
DROP TABLE import;
DROP TABLE search;
CREATE TABLE system (version INTEGER, adminrequest INT DEFAULT 0, reviewrequest INT DEFAULT 0, premiumrequest INT DEFAULT 0);
CREATE TABLE images (imagename STRING, imagetype INTEGER, imagecategory STRING, PRIMARY KEY (imagename));
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon__logo', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bee', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird5', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_bird6', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_butterfly', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_crab', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_beehive', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chick', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chick2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chick3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chick4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chick5', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chicken', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_chicken2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_cow', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_cow2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_cow3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_eggnest', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_pig', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_pig2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_pig3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_pig5', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_sheep', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_sheep2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_sheep3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_farm_sheep4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish6', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish7', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fish8', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_flower', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_flower2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_flower3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_fox', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_guinea_pig', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_horse', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_icecream', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_fly', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_fly2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_fly3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_grasshopper', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_insect', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_ladybird', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_insect_ladybird2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_jungle_lion', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_jungle_lion2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_jungle_lion3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_jungle_lion4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_jungle_monkey', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_dinasaur', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_dragon', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_dragon2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_frog', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_frog2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_hedgehog', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_misc_squirrel', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_owl', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_owl2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_panda', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_cat', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_cat2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_cat3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_dog', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_dog2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_dog3', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_dog4', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_mouse', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_tortoise', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_pet_tortoise2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_rabbit', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_clam', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_crab', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_jellyfish', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_lobster', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_sealion', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_sealion2', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_sea_whale', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_shrimp', 'icon', 'mysettings');
INSERT INTO images (imagename, imagetype, imagecategory) VALUES ('ic_icon_swan', 'icon', 'mysettings');
CREATE TABLE countries (countrycode VARCHAR(2) PRIMARY KEY, country VARCHAR (40), prefix VARCHAR (7));
INSERT INTO countries (countrycode, country, prefix) VALUES ('AF', 'Afghanistan', '+93');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CU', 'Cuba', '+53');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FJ', 'Fiji', '+679');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GU', 'Guam', '+1671');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IR', 'Iran', '+98');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IQ', 'Iraq', '+964');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LA', 'Laos', '+856');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ML', 'Mali', '+223');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NU', 'Niue', '+683');
INSERT INTO countries (countrycode, country, prefix) VALUES ('OM', 'Oman', '+968');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PE', 'Peru', '+51');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TG', 'Togo', '+228');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AW', 'Aruba', '+297');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BJ', 'Benin', '+229');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CL', 'Chile', '+56');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CN', 'China', '+86');
INSERT INTO countries (countrycode, country, prefix) VALUES ('EG', 'Egypt', '+20');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GA', 'Gabon', '+241');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GH', 'Ghana', '+233');
INSERT INTO countries (countrycode, country, prefix) VALUES ('HT', 'Haiti', '+509');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IN', 'India', '+91');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IT', 'Italy', '+39');
INSERT INTO countries (countrycode, country, prefix) VALUES ('JP', 'Japan', '+81');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KE', 'Kenya', '+254');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LY', 'Libya', '+218');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MO', 'Macau', '+853');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MT', 'Malta', '+356');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NR', 'Nauru', '+674');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NP', 'Nepal', '+977');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NE', 'Niger', '+227');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PW', 'Palau', '+680');
INSERT INTO countries (countrycode, country, prefix) VALUES ('QA', 'Qatar', '+974');
INSERT INTO countries (countrycode, country, prefix) VALUES ('WS', 'Samoa', '+685');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ES', 'Spain', '+34');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SD', 'Sudan', '+249');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SY', 'Syria', '+963');
INSERT INTO countries (countrycode, country, prefix) VALUES ('YE', 'Yemen', '+967');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AO', 'Angola', '+244');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BZ', 'Belize', '+501');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BT', 'Bhutan', '+975');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BR', 'Brazil', '+55');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BN', 'Brunei', '+673');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CA', 'Canada', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CY', 'Cyprus', '+357');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FR', 'France', '+33');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GM', 'Gambia', '+220');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GR', 'Greece', '+30');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GN', 'Guinea', '+224');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GY', 'Guyana', '+592');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IL', 'Israel', '+972');
INSERT INTO countries (countrycode, country, prefix) VALUES ('JO', 'Jordan', '+962');
INSERT INTO countries (countrycode, country, prefix) VALUES ('XK', 'Kosovo', '+381');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KW', 'Kuwait', '+965');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LV', 'Latvia', '+371');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MW', 'Malawi', '+265');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MX', 'Mexico', '+52');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MC', 'Monaco', '+377');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NO', 'Norway', '+47');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PA', 'Panama', '+507');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PL', 'Poland', '+48');
INSERT INTO countries (countrycode, country, prefix) VALUES ('RU', 'Russia', '+7');
INSERT INTO countries (countrycode, country, prefix) VALUES ('RW', 'Rwanda', '+250');
INSERT INTO countries (countrycode, country, prefix) VALUES ('RS', 'Serbia', '+381');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SE', 'Sweden', '+46');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TW', 'Taiwan', '+886');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TR', 'Turkey', '+90');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TV', 'Tuvalu', '+688');
INSERT INTO countries (countrycode, country, prefix) VALUES ('UG', 'Uganda', '+256');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ZM', 'Zambia', '+260');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AL', 'Albania', '+355');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DZ', 'Algeria', '+213');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AD', 'Andorra', '+376');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AM', 'Armenia', '+374');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AT', 'Austria', '+43');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BS', 'Bahamas', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BH', 'Bahrain', '+973');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BY', 'Belarus', '+375');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BE', 'Belgium', '+32');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BM', 'Bermuda', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BO', 'Bolivia', '+591');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BI', 'Burundi', '+257');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KM', 'Comoros', '+269');
INSERT INTO countries (countrycode, country, prefix) VALUES ('HR', 'Croatia', '+385');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CW', 'Curacao', '+599');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DK', 'Denmark', '+45');
INSERT INTO countries (countrycode, country, prefix) VALUES ('EC', 'Ecuador', '+593');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ER', 'Eritrea', '+291');
INSERT INTO countries (countrycode, country, prefix) VALUES ('EE', 'Estonia', '+372');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FI', 'Finland', '+358');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GE', 'Georgia', '+995');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DE', 'Germany', '+49');
INSERT INTO countries (countrycode, country, prefix) VALUES ('HU', 'Hungary', '+36');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IS', 'Iceland', '+354');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IE', 'Ireland', '+353');
INSERT INTO countries (countrycode, country, prefix) VALUES ('JM', 'Jamaica', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LB', 'Lebanon', '+961');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LS', 'Lesotho', '+266');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LR', 'Liberia', '+231');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MD', 'Moldova', '+373');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MA', 'Morocco', '+212');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MM', 'Myanmar', '+95');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NA', 'Namibia', '+264');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NG', 'Nigeria', '+234');
INSERT INTO countries (countrycode, country, prefix) VALUES ('RE', 'Reunion', '+262');
INSERT INTO countries (countrycode, country, prefix) VALUES ('RO', 'Romania', '+40');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SN', 'Senegal', '+221');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SO', 'Somalia', '+252');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TK', 'Tokelau', '+690');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TN', 'Tunisia', '+216');
INSERT INTO countries (countrycode, country, prefix) VALUES ('UA', 'Ukraine', '+380');
INSERT INTO countries (countrycode, country, prefix) VALUES ('UY', 'Uruguay', '+598');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VU', 'Vanuatu', '+678');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VA', 'Vatican', '+39');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VN', 'Vietnam', '+84');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AI', 'Anguilla', '+1264');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BB', 'Barbados', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BW', 'Botswana', '+267');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BG', 'Bulgaria', '+359');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KH', 'Cambodia', '+855');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CM', 'Cameroon', '+237');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CO', 'Colombia', '+57');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DJ', 'Djibouti', '+253');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DM', 'Dominica', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ET', 'Ethiopia', '+251');
INSERT INTO countries (countrycode, country, prefix) VALUES ('HN', 'Honduras', '+504');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KI', 'Kiribati', '+686');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MY', 'Malaysia', '+60');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MV', 'Maldives', '+960');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MN', 'Mongolia', '+976');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PK', 'Pakistan', '+92');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PY', 'Paraguay', '+595');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PT', 'Portugal', '+351');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SK', 'Slovakia', '+421');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SI', 'Slovenia', '+386');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SR', 'Suriname', '+597');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TZ', 'Tanzania', '+255');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TH', 'Thailand', '+66');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ZW', 'Zimbabwe', '+263');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AR', 'Argentina', '+54');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AU', 'Australia', '+61');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GI', 'Gibraltar', '+350');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GL', 'Greenland', '+299');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GT', 'Guatemala', '+502');
INSERT INTO countries (countrycode, country, prefix) VALUES ('HK', 'Hong Kong', '+852');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ID', 'Indonesia', '+62');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LT', 'Lithuania', '+370');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MK', 'Macedonia', '+389');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MU', 'Mauritius', '+230');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NI', 'Nicaragua', '+505');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SG', 'Singapore', '+65');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LK', 'Sri Lanka', '+94');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SZ', 'Swaziland', '+268');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VE', 'Venezuela', '+58');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AQ', 'Antarctica', '+672');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AZ', 'Azerbaijan', '+994');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BD', 'Bangladesh', '+880');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CV', 'Cape Verde', '+238');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CR', 'Costa Rica', '+506');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TL', 'East Timor', '+670');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GP', 'Guadeloupe', '+590');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KZ', 'Kazakhstan', '+7');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KG', 'Kyrgyzstan', '+996');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LU', 'Luxembourg', '+352');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MG', 'Madagascar', '+261');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MR', 'Mauritania', '+222');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FM', 'Micronesia', '+691');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ME', 'Montenegro', '+382');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MS', 'Montserrat', '+1664');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MZ', 'Mozambique', '+258');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SM', 'San Marino', '+378');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SC', 'Seychelles', '+248');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TJ', 'Tajikistan', '+992');
INSERT INTO countries (countrycode, country, prefix) VALUES ('UZ', 'Uzbekistan', '+998');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SV', 'El Salvador', '+503');
INSERT INTO countries (countrycode, country, prefix) VALUES ('IM', 'Isle of Man', '+44');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CI', 'Ivory Coast', '+225');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NL', 'Netherlands', '+31');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NZ', 'New Zealand', '+64');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KP', 'North Korea', '+850');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PH', 'Philippines', '+63');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PR', 'Puerto Rico', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LC', 'Saint Lucia', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KR', 'South Korea', '+82');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SS', 'South Sudan', '+211');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CH', 'Switzerland', '+41');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BF', 'Burkina Faso', '+226');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CK', 'Cook Islands', '+682');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SH', 'Saint Helena', '+290');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MF', 'Saint Martin', '+1599');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SA', 'Saudi Arabia', '+966');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SL', 'Sierra Leone', '+232');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ZA', 'South Africa', '+27');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TM', 'Turkmenistan', '+993');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FO', 'Faroe Islands', '+298');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GW', 'Guinea-Bissau', '+245');
INSERT INTO countries (countrycode, country, prefix) VALUES ('LI', 'Liechtenstein', '+423');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NC', 'New Caledonia', '+687');
INSERT INTO countries (countrycode, country, prefix) VALUES ('US', 'United States', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AS', 'American Samoa', '+1684');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KY', 'Cayman Islands', '+1345');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CZ', 'Czech Republic', '+420');
INSERT INTO countries (countrycode, country, prefix) VALUES ('NF', 'Norfolk Island', '+672');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GB', 'United Kingdom', '+44');
INSERT INTO countries (countrycode, country, prefix) VALUES ('EH', 'Western Sahara', '+212');
INSERT INTO countries (countrycode, country, prefix) VALUES ('SB', 'Solomon Islands', '+677');
INSERT INTO countries (countrycode, country, prefix) VALUES ('FK', 'Falkland Islands', '+500');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PF', 'French Polynesia', '+689');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MH', 'Marshall Islands', '+692');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PG', 'Papua New Guinea', '+675');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PN', 'Pitcairn Islands', '+870');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BL', 'Saint Barthélemy', '+590');
INSERT INTO countries (countrycode, country, prefix) VALUES ('GQ', 'Equatorial Guinea', '+240');
INSERT INTO countries (countrycode, country, prefix) VALUES ('DO', 'Dominican Republic', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('TT', 'Trinidad and Tobago', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('AE', 'United Arab Emirates', '+971');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CG', 'Republic of the Congo', '+242');
INSERT INTO countries (countrycode, country, prefix) VALUES ('KN', 'Saint Kitts and Nevis', '+1');
INSERT INTO countries (countrycode, country, prefix) VALUES ('ST', 'Sao Tome and Principe', '+239');
INSERT INTO countries (countrycode, country, prefix) VALUES ('BA', 'Bosnia and Herzegovina', '+387');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VG', 'British Virgin Islands', '+1284');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CF', 'Central African Republic', '+236');
INSERT INTO countries (countrycode, country, prefix) VALUES ('MP', 'Northern Mariana Islands', '+1670');
INSERT INTO countries (countrycode, country, prefix) VALUES ('PM', 'Saint Pierre and Miquelon', '+508');
INSERT INTO countries (countrycode, country, prefix) VALUES ('CD', 'Democratic Republic of Congo', '+243');
INSERT INTO countries (countrycode, country, prefix) VALUES ('VC', 'Saint Vincent and the Grenadines', '+1');
INSERT INTO system (version) VALUES (12);